S03 us#14 creer tutoriel
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #123
Opened 2023-01-16 10:13 UTC by VioletaBD

2023-01-16 14:44 UTC, DrissB45 approved these changes

2023-01-18 13:53 UTC, greegouze approved these changes

2023-01-18 14:49 UTC, sblondeau requested changes
tu as fais tous le CRUD d'un coup plutot que de ne faire que l'ajout

2023-01-18 14:49 UTC, sblondeau commented on src/Entity/Tutorial.php
> +        'Le tutoriel saisie {{ value }} est trop longue, elle ne devrait pas dépasser {{ limit }} caractères',
pareil

2023-01-18 14:49 UTC, sblondeau commented on src/Entity/Tutorial.php
> +    #[Assert\NotBlank(message: 'Le titre est obligatoire et ne peut rester vide.')]
Tu n'a pas besoin réécrire le message en français, tu as déjà un message par défaut qui va s'afficher en français si vous avez bien configurer Symfony

2023-01-18 14:49 UTC, sblondeau commented on src/Controller/AdminTutorialController.php
> +    #[Route('/new', name: 'app_admin_tutorial_new', methods: ['GET', 'POST'])]
route non traduite

2023-01-18 18:13 UTC, DrissB45 commented on templates/admin_tutorial/index.html.twig
> +								<td colspan="3">Aucun enregistrement trouvé</td>
"Aucun tutoriel trouvé" irait peut-être mieux

2023-01-18 18:13 UTC, DrissB45 commented on src/Controller/AdminTutorialController.php
> +            $this->addFlash('success', 'Le nouveau tutoriel a été créé');
tu crées bien un message flash de confirmation dans le controller mais tu ne gères pas son affichage en vue twig. 
Il faudrait configurer ça dans le fichier base.html.twig. 
Aide-toi de cette quête si jamais : https://odyssey.wildcodeschool.com/quests/1025

2023-01-19 11:08 UTC, DrissB45 approved these changes

2023-01-19 11:14 UTC, merged