Fix style login page
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #129
Opened 2023-01-18 17:36 UTC by DrissB45

Fix login page pour matcher la nouvelle maquette

2023-01-18 18:00 UTC, teddyandria submitted a review, later dismissed

2023-01-19 08:16 UTC, sblondeau requested changes

2023-01-19 08:16 UTC, sblondeau commented on templates/components/_header.html.twig
> +				{# <p class="fs-1 fw-bold text-light text-center">{{ title|default('') }}</p> #}
code commenté

2023-01-19 08:16 UTC, sblondeau commented on assets/styles/login.scss
> +    box-shadow: rgba(0, 0, 0, 0.15) 1.95px 1.95px 2.6px;
pourquoi pas 2px ? ça ne me semble pas justifé de mettre des 0.05px :D

2023-01-19 09:07 UTC, VioletaBD submitted a review, later dismissed

2023-01-19 09:34 UTC, sblondeau submitted a review, later dismissed

2023-01-19 10:00 UTC, merged