S03 US19 : Voir les détails d'une leçon
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #147
Opened 2023-01-19 22:06 UTC by DrissB45

2023-01-19 22:54 UTC, teddyandria submitted a review, later dismissed

2023-01-20 08:13 UTC, VioletaBD approved these changes

2023-01-20 09:31 UTC, sblondeau requested changes

2023-01-20 09:31 UTC, sblondeau commented on src/Form/Lesson1Type.php
> +                'mapped' => true,
pourquoi Lesson1 dans le nom ?
si le mapped est true (ce qui me semble le cas) tu peux l'enlèver car c'est la valeur par défaut pour cette option

2023-01-20 09:31 UTC, sblondeau commented on src/Form/Lesson1Type.php
>                      new NotBlank([
les contraites sont à mettre coté Assert dans les entity, pas ici

2023-01-20 10:05 UTC, DrissB45 commented on src/Form/Lesson1Type.php
> +                'mapped' => true,
Ce nom s'est mis automatiquement : LessonType existait déjà pour gérer le quiz

2023-01-20 10:05 UTC, DrissB45 commented on src/Form/Lesson1Type.php
>                      new NotBlank([
Ca ne marchait pas côté Entity, on a trouvé cette solution avec Zakari

2023-01-21 14:24 UTC, greegouze approved these changes

2023-01-23 10:52 UTC, teddyandria approved these changes

2023-01-23 11:56 UTC, sblondeau approved these changes

2023-01-23 11:56 UTC, merged