Creation on the page profil
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #176
Opened 2023-01-23 10:44 UTC by VioletaBD

2023-01-23 13:14 UTC, DrissB45 approved these changes

2023-01-23 13:20 UTC, sblondeau approved these changes

2023-01-25 08:37 UTC, teddyandria submitted a review, later dismissed

2023-01-25 08:57 UTC, sblondeau requested changes

2023-01-25 08:57 UTC, sblondeau commented on migrations/Version20230124112346.php
> +    public function down(Schema $schema): void
pb sur ce fichier, il ne devrait pas être là. 
Tu ne modifie pas la Database dans cette US donc tu n'as pas à faire de make:migration, juste un doctrine:migraiton:migrate 
il faut retirer ce fichier

2023-01-25 09:38 UTC, DrissB45 commented on templates/profil/profil.html.twig
> +			<div class="col">
"col" inutile normalement
Enlève cette classe et regarde si ça change quelque chose mais normalement non

2023-01-25 09:38 UTC, DrissB45 commented on templates/profil/profil.html.twig
> +			<div class="col">
pareil

2023-01-25 10:00 UTC, merged