S03 US10 : Administrer les quiz par leçon
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #182
Opened 2023-01-24 11:20 UTC by DrissB45

2023-01-24 11:34 UTC, greegouze submitted a review, later dismissed

2023-01-24 14:32 UTC, VioletaBD submitted a review, later dismissed

2023-01-24 22:06 UTC, teddyandria submitted a review, later dismissed

2023-01-25 09:10 UTC, VioletaBD submitted a review, later dismissed

2023-01-25 10:31 UTC, sblondeau requested changes

2023-01-25 10:31 UTC, sblondeau commented on migrations/Version20221219210141.php
> +        $this->addSql('CREATE TABLE lesson (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description text NOT NULL, video VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER
hum non tu n'as pas à modifier l'ancienne migration du coup, la nouvelle le fait :o

2023-01-25 10:31 UTC, sblondeau commented on migrations/Version20221219210141.php
> +        $this->addSql('CREATE TABLE lesson (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description text NOT NULL, video VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER
je ne devrais pas voir ce fichier ;-)

2023-01-25 10:31 UTC, sblondeau commented on templates/admin_lesson/_delete_form.html.twig
> +<form method="post" action="{{ path('app_admin_tutorial_lesson_delete', {'id': lesson.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
manque une petite traduction au passage

2023-01-25 10:54 UTC, sblondeau submitted a review, later dismissed

2023-01-25 12:00 UTC, merged