Fix URL nommage
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #213
Opened 2023-01-28 18:37 UTC by DrissB45

Harmonisation des URL

2023-01-28 18:59 UTC, greegouze approved these changes

2023-01-29 22:27 UTC, sblondeau requested changes

2023-01-29 22:27 UTC, sblondeau commented on src/Controller/AdminQuestionController.php
> +    #[Route('/{tutorial}/lecons/{lesson}/quiz/editer', name: 'edit', methods: ['GET', 'POST'])]
ici au pluriel alors que lecon est au singulier partout ailleurs

2023-01-29 22:27 UTC, sblondeau commented on src/Controller/AdminTutorialController.php
> +    #[Route('/tutoriels/ajouter', name: 'new', methods: ['GET', 'POST'])]
idem, chois entre pluriel et singulier partout ,-)

2023-01-30 10:21 UTC, teddyandria submitted a review, later dismissed

2023-01-30 10:36 UTC, sblondeau submitted a review, later dismissed

2023-01-30 11:12 UTC, teddyandria approved these changes

2023-01-30 12:07 UTC, merged