alignContain
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #265
Opened 2023-02-04 21:37 UTC by greegouze

2023-02-05 15:44 UTC, teddyandria approved these changes

2023-02-05 16:06 UTC, DrissB45 submitted a review, later dismissed

2023-02-05 22:19 UTC, sblondeau requested changes

2023-02-05 22:19 UTC, sblondeau commented on src/Controller/LessonController.php
> +                    $this->addFlash('success', 'Bravo, tu a réussi avec au moins 66% de bonnes réponses !');
utilise ta constante plutot que 66% en dur, comme ça si tu décides de changer cette valeur, elle est automatiquement reprise dans le message ;-)

2023-02-06 09:36 UTC, VioletaBD approved these changes

2023-02-06 14:27 UTC, merged