S1 us#5 header
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #53
Opened 2022-12-15 13:02 UTC by VioletaBD

2022-12-15 13:14 UTC, greegouze submitted a review, later dismissed

2022-12-15 13:47 UTC, teddyandria submitted a review, later dismissed

2022-12-15 14:01 UTC, Zakari-B requested changes

2022-12-15 14:01 UTC, Zakari-B commented on templates/layout.html.twig
> +        {% block header %}
A supprimer, il est inutile de le redéfinir si tu extends le template de base et que celui-ci include déjà ton header.

2022-12-15 15:17 UTC, greegouze approved these changes

2022-12-15 16:05 UTC, VioletaBD commented on templates/component/_header.html.twig
> +				<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="text-light bi bi-arrow-left" viewbox="0 0 16 16">
Il n'y en a pas pour le moment mais il devrait changer car il correspond aux noms des tutoriels dans lesquels l'utilisateur se trouve dans la leçon.

2022-12-16 08:43 UTC, greegouze approved these changes

2022-12-16 09:28 UTC, sblondeau approved these changes

2022-12-16 09:28 UTC, merged