S01 US04 : Afficher questions du quiz
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #55
Opened 2022-12-15 13:53 UTC by DrissB45

2022-12-15 14:50 UTC, greegouze submitted a review, later dismissed

2022-12-15 14:58 UTC, Zakari-B requested changes

2022-12-15 14:58 UTC, Zakari-B commented on templates/Components/_quiz.html.twig
> +	{{ encore_entry_link_tags('app') }}
Hum, non ? Le app c'est la fiche de style globale, que tu importes déjà dans ton layout de base, tu n'as pas à le réimporter.

2022-12-15 14:58 UTC, Zakari-B commented on templates/Components/_quiz.html.twig
> +								Faux
Si vrai et faux renvoient la même chose, ça va être compliqué d'avoir bon (ou de se tromper).

2022-12-15 15:00 UTC, sblondeau requested changes
là tu affiches pas la liste de toutes les quesitons, mais tu veux aficher la liste des questions pour UNE leçon données. 
Il faut donc aussi que tu fasses ta relation avec Lesson, linker les fixtures avec LessonFixtures
puis au lieu de fiare un findAll(), aller chercher uniquement les question reliées à cette lesson

2022-12-15 15:02 UTC, sblondeau requested changes

2022-12-15 15:02 UTC, sblondeau commented on templates/Components/_quiz.html.twig
> +							<input class="form-check-input" type="radio" name="reponse1" id="reponse1">
mais la partie réponse devra être fait dans une autre US ! donc je ne dois pas avoir les input radio maintenant ! 
et en plus tu gèreras ça via un form symonfy, donc pas avec des balises input, mais des {{ form_xxx }}

2022-12-16 08:33 UTC, teddyandria submitted a review, later dismissed

2022-12-16 08:44 UTC, teddyandria submitted a review, later dismissed

2022-12-16 08:47 UTC, greegouze submitted a review, later dismissed

2022-12-16 09:38 UTC, sblondeau requested changes

2022-12-16 09:38 UTC, sblondeau commented on src/DataFixtures/LessonFixtures.php
> +            $this->addReference('lesson_' . $lessonName, $lesson);
n'utilise pas le nom de la lesson, mais plus un increment, car avec les espaces dans les noms ça peut poser des pb

2022-12-16 09:38 UTC, sblondeau commented on src/Entity/Question.php
> +    #[ORM\Column(length: 255)]
c'est quoi test ?

2022-12-16 09:38 UTC, sblondeau commented on assets/styles/app.scss
> +@import "home.scss";
webpackconfig => addStyleEntry
https://symfony.com/doc/current/frontend/encore/simple-example.html#compiling-only-a-css-file

2022-12-16 09:38 UTC, sblondeau commented on assets/styles/quiz.scss
> +    background-color: sienna;
variable pour les couleurs

2022-12-19 07:59 UTC, sblondeau requested changes

2022-12-19 07:59 UTC, sblondeau commented on migrations/Version20221215161646.php
> +        // this up() migration is auto-generated, please modify it to your needs
fais en sorte de n'avoir qu'une seule migration par US quand c'est possible (ce qui est le cas là :))

2022-12-19 07:59 UTC, sblondeau commented on migrations/Version20221217212442.php
> +        $this->addSql('ALTER TABLE question ADD text VARCHAR(255) NOT NULL');
idem

2022-12-19 07:59 UTC, sblondeau commented on src/Entity/Question.php
> +    #[ORM\Column(length: 255)]
dsl je vais encore t'embêter mais utilises plutot questionText.
Text étant un mot réservé en sql, tu risques d'avoir potentiellement des problèmes à un moment ;-)

2022-12-19 07:59 UTC, sblondeau commented on src/Entity/Question.php
> +    #[ORM\Column(length: 255)]
au pire tu peux garder text au niveau de ta classe, mais ajouter une anotation pour renommer le champ en bdd, comme j'avais fais avec character

2022-12-19 16:53 UTC, sblondeau requested changes

2022-12-19 16:53 UTC, sblondeau commented on migrations/Version20221215161646.php
> +        // this up() migration is auto-generated, please modify it to your needs
tjs 2 migrations au lieu d'une. 
Supprimes tes fichiers, supprime la table; recréé une seule migration

2022-12-19 16:53 UTC, sblondeau commented on templates/Components/_quiz.html.twig
> +	<div class="accordion col-11 m-auto" id="quiz">
tu es sur pour le col-11 ? généralement un col-12 fonctionne bien... tu es sûr qu'il te manque pas plutot une classe container un une class row ?

2022-12-20 07:59 UTC, sblondeau approved these changes

2022-12-20 09:12 UTC, greegouze approved these changes

2022-12-20 15:38 UTC, merged