US35_page_lesson
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #60
Opened 2022-12-15 20:39 UTC by greegouze

2022-12-15 22:04 UTC, teddyandria submitted a review, later dismissed

2022-12-16 05:46 UTC, VioletaBD approved these changes

2022-12-16 09:42 UTC, sblondeau requested changes

2022-12-16 09:42 UTC, sblondeau commented on assets/styles/home.scss
> +    height: 87%;
a retravailler un peu

2022-12-19 15:49 UTC, teddyandria approved these changes

2022-12-19 16:54 UTC, sblondeau requested changes

2022-12-19 16:54 UTC, sblondeau commented on assets/styles/theme.scss
> +    background: radial-gradient($light, #deedf5);
#deedf5  doit etre dans une variable !

2022-12-19 16:54 UTC, sblondeau commented on templates/lesson/index.html.twig
> +				<div class="col-sm-6 col-md-6 col-lg-6 g-5">
si tu laisse tout à -6, juste un sm-6 suffit (ça s'applique à la taille données ET les plus grandes)

2022-12-20 08:00 UTC, merged