page/tutorial
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #79
Opened 2022-12-22 13:27 UTC by greegouze

2022-12-28 13:52 UTC, teddyandria approved these changes

2022-12-31 11:30 UTC, sblondeau requested changes

2022-12-31 11:30 UTC, sblondeau commented on assets/styles/theme.scss
>  * {
inutile le border-box, c'est déjà de base avec bootstrap

2022-12-31 11:30 UTC, sblondeau commented on src/Controller/LessonController.php
>      #[Route('/show/{id}', requirements: ['id' => '\d+'], name: 'show')]
y a un pb, tu passe Tuto et Lesson en paramètre, or tu n'as qu'un seul param dans l'url
le tuto devrait pouvoir etre déduit de la lesson avec un $lesson->getTutorial() donc inutile de le passer, ça simplifiera

2022-12-31 11:30 UTC, sblondeau commented on templates/component/_header.html.twig
> +			<a class="link active text-start" aria-current="page" href="" onclick="history.back();">
c'est quoi ce lien? faut pas utiliser history.back() c'est pas adapté
tu mets le path() vers la page où tu veux te rediriger

2022-12-31 11:30 UTC, sblondeau commented on templates/component/_navbar.html.twig
> +					<a class="nav-link active" aria-current="page" href="/">
idem ici si tu veux un lien vers la home faut mettre un path() avec le nom de la route de la home, et pas directement le "/"

2023-01-03 13:11 UTC, DrissB45 submitted a review, later dismissed

2023-01-03 14:15 UTC, sblondeau requested changes

2023-01-03 14:15 UTC, sblondeau commented on templates/lesson/index.html.twig
> +{% set return_path = path('tutorial_index', {id: tutorial.id}) %}
hum... tutuorial_index ne prend pas d'id en paramètre non ?

2023-01-03 14:38 UTC, teddyandria approved these changes

2023-01-04 08:29 UTC, sblondeau approved these changes

2023-01-04 09:31 UTC, teddyandria approved these changes

2023-01-04 09:43 UTC, merged