S02 us032 login
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #90
Opened 2023-01-04 14:32 UTC by teddyandria

2023-01-04 14:40 UTC, greegouze approved these changes

2023-01-04 14:51 UTC, DrissB45 approved these changes

2023-01-04 14:51 UTC, DrissB45 commented on src/Repository/UserRepository.php
> +            throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', \get_class($user)));
En français

2023-01-04 14:51 UTC, DrissB45 commented on src/Repository/UserRepository.php
> +//     * @return User[] Returns an array of User objects
Enlever le code commenté

2023-01-04 14:51 UTC, DrissB45 commented on templates/login/index.html.twig
> +{# templates/login/index.html.twig #}
enlever

2023-01-04 14:51 UTC, DrissB45 commented on templates/login/index.html.twig
> +{# ... #}
enlever

2023-01-04 14:51 UTC, DrissB45 commented on templates/login/index.html.twig
> +				{# If you want to control the URL the user is redirected to on success <input type="hidden" name="_target_path" value="/account"> #}
enlever

2023-01-04 15:55 UTC, DrissB45 approved these changes

2023-01-04 16:13 UTC, sblondeau requested changes
remarques de Driss non prises en compte

2023-01-05 08:21 UTC, greegouze submitted a review, later dismissed

2023-01-05 08:27 UTC, sblondeau approved these changes

2023-01-05 09:31 UTC, greegouze approved these changes

2023-01-05 09:35 UTC, Zakari-B approved these changes

2023-01-05 09:36 UTC, merged