S01 US34 : Afficher les réponses du quiz
WildCodeSchool/202209-orleans-php-project-labanquepostale pull request #94
Opened 2023-01-04 18:05 UTC by DrissB45

2023-01-04 21:39 UTC, teddyandria approved these changes

2023-01-05 08:25 UTC, Zakari-B requested changes

2023-01-05 08:25 UTC, Zakari-B commented on src/Controller/LessonController.php
> +                dump($selectedResponse->isIsCorrect());
A retirer

2023-01-05 10:10 UTC, greegouze submitted a review, later dismissed

2023-01-05 10:14 UTC, greegouze approved these changes

2023-01-05 10:16 UTC, merged